import { StyleSheet } from 'react-native';
import colors from '../theme/colors';

const styles = StyleSheet.create({
  welcomeWrap: {
    marginTop: 8,
    backgroundColor: '#EEF3FF',
    borderWidth: 1,
    borderColor: '#D8E2FA',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  welcomeTitle: {
    color: colors.primaryDark,
    fontSize: 16,
    fontWeight: '700',
  },
  welcomeText: {
    marginTop: 4,
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  searchWrap: {
    marginTop: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#D7DFEA99',
    borderRadius: 12,
    padding: 10,
    flexDirection: 'row',
    gap: 8,
    shadowColor: '#1D4E89',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  input: {
    flex: 1,
    backgroundColor: colors.surface2,
    borderWidth: 1.5,
    borderColor: colors.line,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: colors.text,
    fontSize: 13,
  },
  searchBtn: {
    backgroundColor: colors.gold,
    borderRadius: 10,
    justifyContent: 'center',
    paddingHorizontal: 13,
  },
  searchBtnText: {
    color: colors.white,
    fontWeight: '700',
  },
  historyWrap: {
    marginTop: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#D7DFEA99',
    borderRadius: 12,
    padding: 10,
  },
  historyTitle: {
    color: colors.primaryDark,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 8,
  },
  historyList: {
    gap: 8,
  },
  historyItem: {
    backgroundColor: '#EEF3F8',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyCode: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  historyState: {
    color: '#7A86A8',
    fontSize: 12,
  },
  feedbackWrap: {
    marginTop: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: colors.text,
    marginTop: 6,
    fontSize: 13,
  },
  errorText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '500',
  },
  grid: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  quickCard: {
    width: '48%',
    minHeight: 98,
    backgroundColor: '#FFFFFF',
    borderRadius: 11,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.line,
    shadowColor: '#1D4E89',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardTitle: {
    color: colors.primaryDark,
    fontWeight: '700',
    fontSize: 14,
  },
  cardDesc: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 2,
  },
  trackCard: {
    marginTop: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 10,
    shadowColor: '#1D4E89',
    shadowOpacity: 0.1,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  tabsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
  },
  tab: {
    color: '#7F8A9D',
    fontSize: 11,
  },
  tabActive: {
    color: colors.primaryDark,
    fontSize: 11,
    fontWeight: '700',
  },
  trackId: {
    color: colors.primaryDark,
    fontSize: 18,
    fontWeight: '800',
  },
  trackDate: {
    color: '#7F8A9D',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 8,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#9CADCC',
    marginRight: 8,
  },
  timelineText: {
    color: colors.text,
    fontSize: 14,
  },
  timelineRowCurrent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  dotCurrent: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
  },
  timelineCurrentText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  link: {
    marginTop: 2,
    color: colors.muted,
    fontWeight: '500',
    textAlign: 'center',
  },
});

export default styles;