import { StyleSheet } from 'react-native';
import colors from '../theme/colors';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#3A4D8B',
  },
  screenWrap: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 8,
  },
  bgBubbleTop: {
    position: 'absolute',
    top: '15%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF1F',
  },
  bgBubbleBottom: {
    position: 'absolute',
    top: '50%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF14',
  },
  shell: {
    flex: 1,
    width: '100%',
    maxWidth: 375,
    alignSelf: 'center',
    marginHorizontal: 12,
    marginBottom: 10,
    borderRadius: 18,
    backgroundColor: '#FAFBFF',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#FFFFFF66',
    shadowColor: '#2C4A8A',
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  header: {
    backgroundColor: colors.primaryDark,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
  },
  circleBtn: {
    minWidth: 46,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF33',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  circleBtnText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  brandLogo: {
    width: 150,
    height: 70,
    marginLeft: -40,
    transform: [{ scale: 1.85 }],
  },
  brandText: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'serif',
    marginLeft: -22,
  },
  rightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellIcon: {
    width: 14,
    height: 14,
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DCE3F5',
  },
  avatarIcon: {
    width: 18,
    height: 18,
  },
  pageHeading: {
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 10,
  },
  title: {
    color: colors.primaryDark,
    fontSize: 22,
    fontWeight: '600',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  mainArea: {
    padding: 14,
    paddingBottom: 90,
    gap: 12,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 62,
    backgroundColor: '#FBFCFF',
    borderTopWidth: 1,
    borderTopColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navLink: {
    color: '#9AA4BF',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
  },
  navLinkActive: {
    color: colors.primaryDark,
    backgroundColor: '#EAF0FA',
    fontWeight: '700',
  },
});

export default styles;