import { StyleSheet } from 'react-native';
import colors from '../theme/colors';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F2742',
  },
  screenWrap: {
    flex: 1,
    backgroundColor: '#EEF3F8',
    paddingTop: 0,
  },
  bgBubbleTop: {
    position: 'absolute',
    top: '15%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF1A',
  },
  bgBubbleBottom: {
    position: 'absolute',
    top: '50%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF12',
  },
  shell: {
    flex: 1,
    backgroundColor: '#EEF3F8',
    overflow: 'hidden',
  },
  header: {
    paddingHorizontal: 14,
    paddingTop: 34,
    paddingBottom: 18,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginTop: 0,
    overflow: 'hidden',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
  },
  circleBtn: {
    minWidth: 46,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF26',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  circleBtnText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  brandLogo: {
    width: 146,
    height: 64,
    marginLeft: -24,
    marginTop: 2,
    transform: [{ scale: 1.9 }],
  },
  brandText: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'serif',
    marginLeft: -16,
    marginTop: 2,
  },
  rightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF22',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF22',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bellIcon: {
    width: 14,
    height: 14,
  },
  pageHeading: {
    backgroundColor: '#F4F6FB',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: '#DDE3F0',
    borderBottomColor: '#DDE3F0',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centeredSubtitle: {
    color: '#223A5E',
    fontSize: 19,
    fontWeight: '700',
    textAlign: 'center',
  },
  title: {
    color: '#223A5E',
    fontSize: 19,
    fontWeight: '700',
    textAlign: 'center',
  },
  subtitle: {
    marginTop: 4,
    color: '#64748B',
    fontSize: 13,
    textAlign: 'center',
  },
  mainArea: {
    padding: 10,
    paddingBottom: 90,
    gap: 8,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    backgroundColor: '#F2F5F8',
    borderTopWidth: 1,
    borderTopColor: '#D7DFEA',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navBtn: {
    minWidth: 84,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  navBtnActive: {
    backgroundColor: '#EEF3F8',
  },
  navIconWrap: {
    marginBottom: 2,
  },
  navLink: {
    color: '#97A3B8',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 6,
  },
  navLinkActive: {
    color: colors.primaryDark,
    fontWeight: '700',
  },
});

export default styles;