import { StyleSheet } from 'react-native';
import colors from '../theme/colors';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#3A4D8B',
  },
  screenWrap: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 0,
  },
  bgBubbleTop: {
    position: 'absolute',
    top: '15%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF1F',
  },
  bgBubbleBottom: {
    position: 'absolute',
    top: '50%',
    left: '-30%',
    width: '160%',
    height: '75%',
    borderRadius: 999,
    backgroundColor: '#FFFFFF14',
  },
  shell: {
    flex: 1,
    width: '100%',
    maxWidth: 375,
    alignSelf: 'center',
    marginHorizontal: 12,
    marginBottom: 10,
    borderRadius: 18,
    backgroundColor: '#FAFBFF',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#FFFFFF66',
    shadowColor: '#2C4A8A',
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  header: {
    paddingHorizontal: 14,
    paddingTop: 34,
    paddingBottom: 18,
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    marginTop: 0,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
  },
  circleBtn: {
    minWidth: 46,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF33',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  circleBtnText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  brandLogo: {
    width: 146,
    height: 64,
    marginLeft: -24,
    marginTop: 2,
    transform: [{ scale: 1.9 }],
  },
  brandText: {
    color: colors.white,
    fontSize: 26,
    fontWeight: '700',
    fontFamily: 'serif',
    marginLeft: -16,
    marginTop: 2,
  },
  rightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF2E',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  bellIcon: {
    width: 14,
    height: 14,
  },
  pageHeading: {
    backgroundColor: '#F4F6FB',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: '#DDE3F0',
    borderBottomColor: '#DDE3F0',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centeredSubtitle: {
    color: '#1F3762',
    fontSize: 19,
    fontWeight: '700',
    textAlign: 'center',
  },
  mainArea: {
    padding: 14,
    paddingBottom: 90,
    gap: 12,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 66,
    backgroundColor: '#FBFCFF',
    borderTopWidth: 1,
    borderTopColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  navBtn: {
    minWidth: 84,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  navBtnActive: {
    backgroundColor: '#EAF0FA',
  },
  navIconWrap: {
    marginBottom: 2,
  },
  navLink: {
    color: '#9AA4BF',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 6,
  },
  navLinkActive: {
    color: colors.primaryDark,
    fontWeight: '700',
  },
});

export default styles;