import { StyleSheet } from 'react-native';
import colors from '../theme/colors';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0F2742',
  },
  gradientBackground: {
    flex: 1,
  },
  keyboardWrap: {
    flex: 1,
  },
  waveOne: {
    position: 'absolute',
    width: '215%',
    height: 260,
    left: '-64%',
    top: '30%',
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.13)',
    transform: [{ rotate: '-6deg' }],
  },
  waveTwo: {
    position: 'absolute',
    width: '220%',
    height: 230,
    left: '-60%',
    top: '50%',
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    transform: [{ rotate: '-4deg' }],
  },
  waveThree: {
    position: 'absolute',
    width: '230%',
    height: 230,
    left: '-72%',
    top: '74%',
    borderRadius: 9999,
    backgroundColor: 'rgba(255, 255, 255, 0.07)',
    transform: [{ rotate: '-3deg' }],
  },
  container: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  content: {
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    zIndex: 2,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  backBtn: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  backBtnText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  card: {
    backgroundColor: '#F7F9FC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D7DFEA',
    padding: 18,
    shadowColor: '#31466A',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 6,
  },
  title: {
    color: colors.primaryDark,
    fontSize: 21,
    fontWeight: '800',
  },
  subtitle: {
    marginTop: 4,
    marginBottom: 14,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  inputLabel: {
    marginBottom: 6,
    color: '#4B5D7A',
    fontWeight: '600',
    fontSize: 12,
  },
  input: {
    backgroundColor: '#EEF3F8',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
    color: colors.text,
    fontSize: 14,
  },
  helperText: {
    color: '#6A7895',
    fontSize: 12,
    marginTop: -2,
    marginBottom: 10,
  },
  primaryBtn: {
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 2,
  },
  primaryBtnDisabled: {
    opacity: 0.7,
  },
  primaryBtnGradient: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  errorWrap: {
    backgroundColor: '#FFE5E5',
    borderWidth: 1,
    borderColor: '#FF6B6B',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
  },
  errorText: {
    color: '#B42318',
    fontSize: 13,
    fontWeight: '500',
  },
  loadingWrap: {
    marginTop: 10,
    alignItems: 'center',
  },
  loadingText: {
    color: '#4A5B79',
    marginTop: 6,
    fontSize: 13,
  },
  resultCard: {
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D7DFEA',
    borderRadius: 12,
    padding: 12,
  },
  resultCode: {
    color: colors.primaryDark,
    fontSize: 17,
    fontWeight: '800',
  },
  resultSummary: {
    marginTop: 3,
    color: '#5F6B84',
    fontSize: 12,
  },
  statusPill: {
    alignSelf: 'flex-start',
    marginTop: 9,
    borderRadius: 999,
    backgroundColor: '#E8F1FF',
    borderWidth: 1,
    borderColor: '#B8D0F3',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusPillText: {
    color: '#1D4E89',
    fontSize: 12,
    fontWeight: '700',
  },
  timelineWrap: {
    marginTop: 10,
    gap: 8,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 4,
    marginRight: 8,
    backgroundColor: '#A1B1CF',
  },
  timelineDotCurrent: {
    backgroundColor: colors.gold,
  },
  timelineState: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '600',
  },
  timelineMeta: {
    marginTop: 2,
    color: '#7382A2',
    fontSize: 11,
  },
  timelineNote: {
    marginTop: 1,
    color: '#5F6B84',
    fontSize: 11,
  },
});

export default styles;
