import { StyleSheet } from 'react-native';
import colors from '../../theme/colors';

export default function getDashboardRStyles(s) {
	return StyleSheet.create({
		nativeRoot: {
			flex: 1,
		},
		webRoot: {
			flex: 1,
			backgroundColor: '#DCE4F3',
			alignItems: 'center',
			justifyContent: 'center',
			paddingVertical: s(12),
		},
		safeArea: {
			flex: 1,
			backgroundColor: colors.primaryDark,
		},
		header: {
			height: s(56),
			backgroundColor: colors.primaryDark,
			paddingHorizontal: s(12),
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		brandWrap: {
			flexDirection: 'row',
			alignItems: 'center',
			gap: s(4),
		},
		headerLogo: {
			width: s(90),
			height: s(34),
		},
		brandText: {
			color: colors.white,
			fontSize: s(16),
			fontWeight: '600',
			letterSpacing: 0.6,
		},
		headerRight: {
			flexDirection: 'row',
			alignItems: 'center',
			gap: s(8),
		},
		bellWrap: {
			width: s(20),
			height: s(20),
			alignItems: 'center',
			justifyContent: 'center',
			position: 'relative',
		},
		bellText: {
			color: '#D9E4FF',
			fontSize: s(12),
			fontWeight: '700',
		},
		bellBadge: {
			position: 'absolute',
			top: -1,
			right: -2,
			width: s(11),
			height: s(11),
			borderRadius: s(6),
			backgroundColor: colors.gold,
			alignItems: 'center',
			justifyContent: 'center',
		},
		bellBadgeText: {
			color: colors.white,
			fontSize: s(7),
			fontWeight: '700',
		},
		avatarCircle: {
			width: s(30),
			height: s(30),
			borderRadius: s(15),
			backgroundColor: '#D6E3FB',
			borderColor: colors.white,
			borderWidth: 2,
			alignItems: 'center',
			justifyContent: 'center',
		},
		avatarText: {
			color: colors.primaryDark,
			fontWeight: '700',
			fontSize: s(10),
		},
		content: {
			backgroundColor: '#EAF0FA',
			paddingHorizontal: s(10),
			paddingTop: s(10),
			paddingBottom: s(12),
			gap: s(8),
		},
		welcome: {
			color: '#2D467C',
			fontSize: s(24),
			fontWeight: '700',
		},
		serviceRow: {
			flexDirection: 'row',
			alignItems: 'center',
			gap: s(6),
			marginTop: s(-2),
		},
		onlineDot: {
			width: s(7),
			height: s(7),
			borderRadius: s(4),
			backgroundColor: '#4CB36C',
		},
		serviceText: {
			color: '#8090B8',
			fontSize: s(12),
		},
		statsRow: {
			flexDirection: 'row',
			gap: s(8),
		},
		statCard: {
			flex: 1,
			borderRadius: s(9),
			borderWidth: 1,
			borderColor: '#D9E1F1',
			backgroundColor: '#F6F8FE',
			flexDirection: 'row',
			alignItems: 'center',
			gap: s(8),
			paddingHorizontal: s(8),
			paddingVertical: s(8),
		},
		statIconBlue: {
			width: s(24),
			height: s(24),
			borderRadius: s(8),
			backgroundColor: '#61A2D8',
			alignItems: 'center',
			justifyContent: 'center',
		},
		statIconGold: {
			width: s(24),
			height: s(24),
			borderRadius: s(8),
			backgroundColor: '#F1D078',
			alignItems: 'center',
			justifyContent: 'center',
		},
		statIconText: {
			color: colors.white,
			fontWeight: '700',
			fontSize: s(9),
		},
		statTitle: {
			color: '#2A4D8C',
			fontWeight: '700',
			fontSize: s(13),
			lineHeight: s(15),
		},
		statValue: {
			color: '#365484',
			fontWeight: '700',
			fontSize: s(16),
			lineHeight: s(18),
		},
		card: {
			borderRadius: s(10),
			borderWidth: 1,
			borderColor: '#D9E0EF',
			backgroundColor: '#EEF2FB',
			padding: s(9),
		},
		singleBox: {
			height: s(170),
			borderRadius: s(10),
			borderWidth: 1,
			borderColor: '#D1D8E5',
			backgroundColor: '#DDE3EE',
		},
		searchRow: {
			marginBottom: s(8),
		},
		searchInputWrap: {
			flex: 1,
			borderWidth: 1,
			borderColor: '#D6DEEE',
			borderRadius: s(8),
			backgroundColor: '#F5F8FE',
			flexDirection: 'row',
			alignItems: 'center',
			paddingHorizontal: s(8),
		},
		searchPrefix: {
			color: '#7A88A8',
			fontSize: s(11),
			fontWeight: '700',
		},
		searchInput: {
			flex: 1,
			color: '#4A5D85',
			fontSize: s(12),
			paddingHorizontal: s(6),
			paddingVertical: s(8),
		},
		sortRow: {
			marginBottom: s(8),
		},
		sortText: {
			color: '#7583A6',
			fontSize: s(11),
		},
		singleRecord: {
			paddingVertical: s(8),
			gap: s(5),
			borderRadius: s(10),
			borderWidth: 1,
			borderColor: '#D9E0EF',
			backgroundColor: '#E8EDF8',
			paddingHorizontal: s(8),
		},
		recordTopRow: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		recordIdWrap: {
			flexDirection: 'row',
			alignItems: 'center',
			gap: s(6),
		},
		recordDot: {
			width: s(10),
			height: s(10),
			borderRadius: s(5),
			borderWidth: 2,
			borderColor: '#EAA729',
		},
		recordId: {
			color: '#5B6B90',
			fontSize: s(10),
		},
		recordTime: {
			color: '#4F6795',
			fontWeight: '600',
			fontSize: s(12),
		},
		recordBottomRow: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'flex-end',
			gap: s(8),
		},
		recordInfo: {
			flex: 1,
		},
		recordName: {
			color: '#27467B',
			fontWeight: '700',
			fontSize: s(16),
			lineHeight: s(19),
		},
		recordAddress: {
			color: '#4F638D',
			fontSize: s(11),
		},
		recordActionBtn: {
			borderRadius: s(7),
			minWidth: s(96),
			paddingHorizontal: s(10),
			paddingVertical: s(5),
			alignItems: 'center',
			backgroundColor: '#F2AB2A',
		},
		recordActionText: {
			color: colors.white,
			fontWeight: '700',
			fontSize: s(10),
		},
		tipCard: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'flex-end',
			marginBottom: s(6),
		},
		tipTextWrap: {
			flex: 1,
			paddingRight: s(8),
		},
		tipTitle: {
			color: '#405D8E',
			fontWeight: '700',
			fontSize: s(15),
			marginBottom: s(3),
		},
		tipBody: {
			color: '#617399',
			fontSize: s(11),
			marginBottom: s(5),
		},
		tipLink: {
			color: '#3F67A8',
			fontWeight: '600',
			fontSize: s(12),
		},
		tipAvatar: {
			width: s(52),
			height: s(52),
			borderRadius: s(26),
			borderWidth: 2,
			borderColor: '#C6D4EE',
			backgroundColor: '#D8E3F8',
			alignItems: 'center',
			justifyContent: 'center',
		},
		tipAvatarText: {
			color: colors.primaryDark,
			fontWeight: '700',
			fontSize: s(14),
		},
	});
}
