import { StyleSheet } from 'react-native';
import colors from '../../theme/colors';

export default function getEntregasRStyles(s) {
  return StyleSheet.create({
    nativeRoot: { flex: 1 },
    webRoot: {
      flex: 1,
      backgroundColor: '#DCE5F5',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: s(12),
    },
    safeArea: {
      flex: 1,
      backgroundColor: colors.primaryDark,
    },
    topHeader: {
      height: s(56),
      backgroundColor: colors.primaryDark,
      paddingHorizontal: s(14),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    topHeaderTitle: {
      color: colors.white,
      fontSize: s(16),
      fontWeight: '700',
    },
    avatarCircle: {
      width: s(30),
      height: s(30),
      borderRadius: s(15),
      backgroundColor: '#D6E3FB',
      borderWidth: 2,
      borderColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      flex: 1,
      backgroundColor: '#EAF0FA',
      paddingHorizontal: s(10),
      paddingTop: s(10),
    },
    secondTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(8),
      marginBottom: s(10),
    },
    secondTitle: {
      color: '#2C4A8A',
      fontSize: s(30),
      fontWeight: '700',
      lineHeight: s(32),
    },
    searchWrap: {
      borderWidth: 1,
      borderColor: '#D5DEEF',
      borderRadius: s(8),
      backgroundColor: '#F3F7FE',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: s(10),
      marginBottom: s(10),
    },
    searchInput: {
      flex: 1,
      color: '#556A95',
      fontSize: s(13),
      paddingHorizontal: s(8),
      paddingVertical: s(9),
    },
    filtersRow: {
      borderRadius: s(8),
      borderWidth: 1,
      borderColor: '#D6DEEE',
      backgroundColor: '#ECF2FD',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: s(8),
      paddingVertical: s(8),
      marginBottom: s(12),
      gap: s(10),
    },
    filterText: {
      color: '#3F5E98',
      fontWeight: '700',
      fontSize: s(12),
    },
    filterTextMuted: {
      color: '#4E679D',
      fontWeight: '600',
      fontSize: s(12),
    },
    sectionCard: {
      flex: 1,
      borderRadius: s(10),
      borderWidth: 1,
      borderColor: '#D9E1F0',
      backgroundColor: '#EDF2FC',
      paddingHorizontal: s(8),
      paddingTop: s(10),
    },
    sectionTitle: {
      color: '#2F4E8D',
      fontSize: s(22),
      fontWeight: '700',
      marginBottom: s(8),
    },
    listContent: {
      paddingBottom: s(14),
      gap: s(8),
    },
    deliveryCard: {
      borderRadius: s(10),
      borderWidth: 1,
      borderColor: '#D7DFEF',
      backgroundColor: '#F6F9FF',
      paddingHorizontal: s(10),
      paddingVertical: s(10),
      gap: s(6),
    },
    deliveryTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: s(8),
    },
    codeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: s(6),
      flex: 1,
    },
    pinWrap: {
      width: s(18),
      height: s(18),
      borderRadius: s(9),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#EED8A8',
    },
    pinBlue: {
      backgroundColor: '#C8D5F0',
    },
    pinDot: {
      width: s(7),
      height: s(7),
      borderRadius: s(4),
      backgroundColor: '#E0A72E',
    },
    pinDotBlue: {
      backgroundColor: '#3E5F9A',
    },
    deliveryCode: {
      color: '#667AA6',
      fontSize: s(14),
      fontWeight: '500',
    },
    actionBtn: {
      minWidth: s(94),
      borderRadius: s(8),
      backgroundColor: '#6EA9E6',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: s(8),
      paddingHorizontal: s(8),
    },
    actionBtnDone: {
      backgroundColor: '#75B9C8',
    },
    actionText: {
      color: colors.white,
      fontWeight: '700',
      fontSize: s(14),
    },
    deliveryName: {
      color: '#2B4579',
      fontSize: s(21),
      fontWeight: '700',
      lineHeight: s(24),
    },
    deliveryAddress: {
      color: '#536A95',
      fontSize: s(13),
      lineHeight: s(18),
    },
  });
}
